name: Test
on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22]
    steps:
      - uses: ./.github/workflows/base.yaml
        with:
          node-version: ${{ matrix.node-version }}
